name: "Podcast Generator"
author: "Adrian Tadeo"
description: "Generates a feed for a podcast from a YAML file"

inputs:
  email:
    description: "The committer's email address"
    required: true
    default: "actor@localhost"
  name:
    description: "The committer's name"
    required: true
    default: "actor"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "yellow"
